version: "3"
services:
  zookeeper:
    container_name: dc-kafka-zookeeper
    env_file:
      - zookeeper.env
    image: zookeeper:latest
    networks:
      - nw-kafka
    ports:
      - "2181:2181" # the zookeeper client port
      # - "2888:2888" # follower port
      # - "3888:3888" # election port
      # - "8080:8080" # AdminServer port respectively
    restart: always
    tty: true
    # volumes:
    #    - ./zookeeper-conf:/conf
    #   - ./zookeeper-data:/data
    #   - ./zookeeper-datalog:/datalog
    #   - ./zookeeper-logs:/logs

  kafka:
    build:
      args:
        KAFKA_VERSION: ${KAFKA_VERSION}
        SCALA_VERSION: ${SCALA_VERSION}
      context: ./kafka
    command:
      - "kafka-server-start"
      - "/kafka/config/server.properties"
      - "--override"
      - "zookeeper.connect=dc-kafka-zookeeper"
      # Refer to:
      # https://www.confluent.io/blog/kafka-listeners-explained/
      - "--override"
      - "listeners=LISTENER_BOB://dc-kafka:29092,LISTENER_FRED://0.0.0.0:9092"
      - "--override"
      - "advertised.listeners=LISTENER_BOB://dc-kafka:29092,LISTENER_FRED://localhost:9092"
      - "--override"
      - "listener.security.protocol.map=LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT"
      - "--override"
      - "inter.broker.listener.name=LISTENER_BOB"
    container_name: dc-kafka
    depends_on:
      - zookeeper
    env_file:
      - kafka.env
    image: grammyjiang/kafka:${KAFKA_VERSION}
    networks:
      - nw-kafka
    ports:
      - "9092:9092"
    restart: always
    tty: true
    # volumes:
    #   - "./kafka-config:/kafka/config"

networks:
  nw-kafka:
    driver: bridge
